ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS nombre VARCHAR(80);

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS apellido VARCHAR(80);

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS telefono VARCHAR(30);

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS foto_url VARCHAR(500);