ALTER TABLE pago
ADD COLUMN IF NOT EXISTS anulado BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE pago
ADD COLUMN IF NOT EXISTS fecha_anulacion TIMESTAMP;

ALTER TABLE pago
ADD COLUMN IF NOT EXISTS motivo_anulacion VARCHAR(255);