spring.application.name=demo

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/club_banco
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=CAMBIAME_ESTE_SECRETO_LARGO_32CHARS_MINIMO_123456
app.jwt.expiration-minutes=240

# Mercado Pago
mp.access-token=TEST-ACCESS-TOKEN-AQUI
mp.webhook-secret=  # opcional (si usás firma)
mp.front.success-url=http://localhost:4200/pago-exitoso
mp.front.pending-url=http://localhost:4200/pago-pendiente
mp.front.failure-url=http://localhost:4200/pago-fallido

# ===============================
# LOGGING (opcional para debug SQL)
# ===============================
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
