spring.application.name=demo

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATASOURCE (Supabase PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

 spring.profiles.active=local
# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:240}

# Mercado Pago
mp.access-token=${MP_ACCESS_TOKEN:TEST-ACCESS-TOKEN-AQUI}
mp.webhook-secret=${MP_WEBHOOK_SECRET:}
mp.front.success-url=${MP_FRONT_SUCCESS_URL:http://localhost:4200/pago-exitoso}
mp.front.pending-url=${MP_FRONT_PENDING_URL:http://localhost:4200/pago-pendiente}
mp.front.failure-url=${MP_FRONT_FAILURE_URL:http://localhost:4200/pago-fallido}

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace