spring.application.name=demo

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (LOCAL / SUPABASE DIRECTO)
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pvitwzzkdhqsyhosjhou
spring.datasource.password=Cb!2026_Supabase_DB_Segura_#1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# JWT
# ===============================
app.jwt.secret=app.jwt.secret=mi_clave_jwt_super_segura_club_banco_2026
app.jwt.expiration-minutes=240

# ===============================
# MERCADO PAGO
# ===============================
mp.access-token=TEST-ACCESS-TOKEN-AQUI
mp.webhook-secret=
mp.front.success-url=http://localhost:4200/pago-exitoso
mp.front.pending-url=http://localhost:4200/pago-pendiente
mp.front.failure-url=http://localhost:4200/pago-fallido

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace